spring:
  datasource:
   url: jdbc:mysql://localhost:3306/fnxt_pfm_local?useTimezone=true&serverTimezone=Asia/Kathmandu
   username: root
   password: MySQL1*#
    # url: jdbc:mysql://10.13.194.238:3311/fnxt_pfm_dev?useTimezone=true&serverTimezone=Asia/Kathmandu
    # username: fonenxt
    # password: f1s0ft@123
      
  zipkin:
    baseUrl: http://localhost:9411/
  kafka:
    producer:
      bootstrap-servers: http://localhost:9092
    consumer:
      bootstrap-servers: http://localhost:9092

cbs-middleware:
  baseUrl : http://dev-cbs-middleware.fonenext-dev.10.13.194.202.nip.io
  admin.username : Admin
  admin.password : password
  client.api:
    key : Clinet2
    secret: secret
  date.format : yyyy-MM-dd

customer-api:
  url: http://localhost:8081/api
